import type { GameEvent } from '../../types'

function escapeSingleQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function formatEventEntry(event: GameEvent): string {
  const [red, green, blue] = event.color
  return `  {
    id: '${escapeSingleQuoted(event.id)}',
    name: '${escapeSingleQuoted(event.name)}',
    tag: '${escapeSingleQuoted(event.tag)}',
    banner: '${escapeSingleQuoted(event.banner)}',
    color: [${red}, ${green}, ${blue}],
    startDate: '${event.startDate}',
    endDate: '${event.endDate}',
  },`
}

export function generateEventsFileSource(events: GameEvent[]): string {
  const entries = events.map(formatEventEntry).join('\n')

  return `import type { GameEvent } from '../types'

// Dates follow the Global server schedule (UTC-7), sourced from
// https://arknights.wiki.gg/wiki/Event. Colors are hand-picked from each
// event's banner art (or averaged automatically for entries added by the
// daily sync) to drive the accent used on Dashboard cards and the
// Calendar's date-range bars.
//
// Regenerated by /api/cron/scrape-events: existing entries are matched by
// \`name\` and only have their dates refreshed, new entries are appended —
// hand edits to tag/color/banner on existing entries are preserved.
export const EVENTS: GameEvent[] = [
${entries}
]
`
}
